# rate
rate_ros: 200.0
rate_odom: 100.0

# model
model_base: "base_link"
model_odom: "odom"

# limit
limit_vel:
  # [vel_norm, omega]
  - 0.5
  - 1.57
limit_acc:
  # [acc_norm, alpha]
  - 6.0
  - 3.14

# obs
obs_weights: 0.3

# trace
trace_pid:
  # [kp_x, kp_yaw]
  # [ki_x, ki_yaw]
  # [kd_x, kd_yaw]
  - "[100.0, 100.0]"
  - "[0.0, 0.0]"
  - "[20.0, 20.0]"
trace_err_limit:
  # [pos_err, yaw_err]
  - 0.5
  - 1.0
trace_stanley: 0.0
